bind_addr = ":8080"
log_level = "debug"

[store]
database_url = "postgres://postgres:postgres@localhost/restapi_dev?sslmode=disable"
# database_url = "host=localhost user=postgres password=postgres dbname=restapi_dev sslmode=disable"